# Generated by Django 5.0.2 on 2025-04-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantUe',
            fields=[
                ('id_etudiant_ue', models.AutoField(primary_key=True, serialize=False)),
                ('annee_scolaire', models.CharField(blank=True, max_length=9, null=True)),
                ('note_initiale', models.FloatField(blank=True, null=True)),
                ('note_rattrapage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etudiant_ue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anonymat',
            fields=[
                ('id_anonymat', models.AutoField(primary_key=True, serialize=False)),
                ('numero_anonymat', models.CharField(max_length=50, unique=True)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('id_etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, to='api.etudiant')),
            ],
            options={
                'db_table': 'anonymat',
            },
        ),
    ]
